# AWS Elastic Beanstalk Enterprise Production Configuration
# QuantumVest Legendary Investor Platform - Production Deployment

# Environment Configuration
option_settings:
  # Application Environment
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: production

    # Core Application Variables (Updated for Vite)
    VITE_APP_NAME: QuantumVest Enterprise
    VITE_APP_VERSION: 2.1.0
    VITE_APP_ENV: production
    VITE_DEPLOYMENT_PLAN: production
    VITE_SITE_URL: https://quantumvest.app
    VITE_DEBUG_MODE: false
    VITE_BUNDLE_ANALYZER: false
    GENERATE_SOURCEMAP: false

    # API Configuration
    VITE_API_URL: https://api.quantumvest.app
    VITE_API_BASE_URL: https://api.quantumvest.app
    VITE_WEBSOCKET_URL: wss://ws.quantumvest.app
    VITE_CDN_URL: https://cdn.quantumvest.app

    # Enterprise Features
    VITE_ENABLE_ENTERPRISE_FEATURES: true
    VITE_ENABLE_LEGENDARY_INVESTORS: true
    VITE_ENABLE_AI_EXPLAINABILITY: true
    VITE_ENABLE_MOBILE_MANAGEMENT: true
    VITE_ENABLE_GLOBAL_EXPANSION: true
    VITE_ENABLE_QUANTUM_FEATURES: true

    # Payment & Billing (Updated for Vite)
    VITE_STRIPE_PUBLIC_KEY: pk_live_YOUR_STRIPE_LIVE_PUBLIC_KEY
    VITE_STRIPE_SECRET_KEY: sk_live_YOUR_STRIPE_LIVE_SECRET_KEY
    VITE_PAYPAL_CLIENT_ID: YOUR_PAYPAL_LIVE_CLIENT_ID
    VITE_PAYPAL_ENVIRONMENT: live
    VITE_PAYSTACK_PUBLIC_KEY: pk_live_YOUR_PAYSTACK_LIVE_PUBLIC_KEY
    VITE_PAYSTACK_ENVIRONMENT: live

    # Demo Access Configuration
    VITE_DEMO_ENABLED: true
    VITE_DEMO_DURATION_HOURS: 1
    VITE_DEMO_EXTENSION_MINUTES: 15

    # Route Configuration (Legacy React App format for compatibility)
    REACT_APP_FREE_TIER_ROUTES: "/, /dashboard, /pricing, /billing, /archetypes, /age-switcher-demo, /game-layout-demo, /enterprise-subscriptions"
    REACT_APP_STARTER_TIER_ROUTES: "/retail-investor, /emerging-market-citizen, /student-early-career"
    REACT_APP_PROFESSIONAL_TIER_ROUTES: "/financial-advisor, /cultural-investor, /diaspora-investor, /developer-integrator, /public-sector-ngo, /quant-data-driven-investor, /geographical-consciousness"
    REACT_APP_ENTERPRISE_TIER_ROUTES: "/institutional-investor, /african-market-enterprise, /wildlife-conservation-enterprise, /quantum-enterprise-2050, /legendary-investors-enterprise, /methuselah-enterprise, /tortoise-protocol"

    # Analytics & Monitoring (Updated for Vite)
    VITE_GOOGLE_ANALYTICS_ID: G-YOUR_PRODUCTION_GA_ID
    VITE_MIXPANEL_TOKEN: YOUR_PRODUCTION_MIXPANEL_TOKEN
    VITE_SENTRY_DSN: https://YOUR_PRODUCTION_SENTRY_DSN@sentry.io/PROJECT_ID
    VITE_HOTJAR_ID: YOUR_HOTJAR_ID
    VITE_ANALYTICS_ID: GA_PRODUCTION_ID

    # Security & Authentication (Updated for Vite)
    VITE_AUTH0_DOMAIN: quantumvest.us.auth0.com
    VITE_AUTH0_CLIENT_ID: YOUR_PRODUCTION_AUTH0_CLIENT_ID
    VITE_AUTH0_AUDIENCE: https://api.quantumvest.app
    VITE_SUPABASE_URL: https://YOUR_PRODUCTION_PROJECT.supabase.co
    VITE_SUPABASE_ANON_KEY: YOUR_PRODUCTION_SUPABASE_ANON_KEY

    # Google Services
    VITE_GOOGLE_MAPS_API_KEY: YOUR_PRODUCTION_GOOGLE_MAPS_API_KEY
    REACT_APP_GOOGLE_MAPS_API_KEY: YOUR_PRODUCTION_GOOGLE_MAPS_API_KEY

    # AWS Services Integration
    VITE_AWS_REGION: us-east-1
    VITE_AWS_S3_BUCKET: quantumvest-production-assets
    VITE_AWS_CLOUDFRONT_DISTRIBUTION_ID: YOUR_CLOUDFRONT_DISTRIBUTION_ID
    AWS_REGION: us-east-1
    AWS_S3_BUCKET: quantumvest-production-assets
    AWS_SES_REGION: us-east-1
    AWS_SNS_TOPIC_ARN: arn:aws:sns:us-east-1:YOUR_ACCOUNT_ID:quantumvest-notifications

    # Database & Cache
    DATABASE_URL: postgresql://user:password@quantumvest-prod.YOUR_RDS_ENDPOINT.us-east-1.rds.amazonaws.com:5432/quantumvest
    VITE_REDIS_URL: rediss://YOUR_PRODUCTION_REDIS_URL
    REDIS_URL: redis://quantumvest-prod.YOUR_ELASTICACHE_ENDPOINT.cache.amazonaws.com:6379

    # AI & ML Services (Updated for Vite)
    VITE_OPENAI_API_KEY: sk-prod_YOUR_OPENAI_API_KEY
    VITE_ANTHROPIC_API_KEY: sk-ant-YOUR_ANTHROPIC_API_KEY
    VITE_GOOGLE_AI_API_KEY: AIzaSy_YOUR_GOOGLE_AI_API_KEY
    VITE_ALADDIN_API_KEY: YOUR_PRODUCTION_ALADDIN_API_KEY

    # Custom AI Models
    VITE_RISK_MODEL_ENDPOINT: https://ml.quantumvest.app/risk-model
    VITE_CULTURAL_SCREENING_ENDPOINT: https://ml.quantumvest.app/cultural-screening
    VITE_MARKET_SENTIMENT_ENDPOINT: https://ml.quantumvest.app/market-sentiment

    # Legendary Investor Services (Updated for Vite)
    VITE_MUNGER_MENTAL_MODELS_API_KEY: mm_production_api_key_here
    VITE_MUNGER_API_ENDPOINT: https://ai.quantumvest.app/munger
    VITE_BUFFETT_MOAT_ANALYSIS_API_KEY: bm_production_api_key_here
    VITE_BUFFETT_API_ENDPOINT: https://ai.quantumvest.app/buffett
    VITE_DALIO_SYSTEMS_API_KEY: ds_production_api_key_here
    VITE_DALIO_API_ENDPOINT: https://ai.quantumvest.app/dalio
    VITE_LYNCH_INSIGHTS_API_KEY: li_production_api_key_here
    VITE_LYNCH_API_ENDPOINT: https://ai.quantumvest.app/lynch

    # Market Data Providers (Updated for Vite)
    VITE_ALPHA_VANTAGE_API_KEY: YOUR_PRODUCTION_ALPHA_VANTAGE_KEY
    VITE_FINNHUB_API_KEY: YOUR_PRODUCTION_FINNHUB_KEY
    VITE_POLYGON_IO_API_KEY: YOUR_PRODUCTION_POLYGON_IO_KEY
    VITE_QUANDL_API_KEY: YOUR_PRODUCTION_QUANDL_KEY

    # Compliance & Regulatory
    COMPLIANCE_REPORTING_ENABLED: true
    GDPR_COMPLIANCE_ENABLED: true
    SOC2_COMPLIANCE_ENABLED: true
    PCI_DSS_COMPLIANCE_ENABLED: true

  # Platform Configuration
  aws:elasticbeanstalk:environment:
    EnvironmentType: LoadBalanced
    LoadBalancerType: application
    ServiceRole: aws-elasticbeanstalk-service-role

  # Auto Scaling Configuration
  aws:autoscaling:asg:
    MinSize: 3
    MaxSize: 20
    Availability Zones: Any 3

  aws:autoscaling:launchconfiguration:
    InstanceType: t3.large
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    SecurityGroups: sg-xxxxxxxxxxxxxxxxx
    EC2KeyName: quantumvest-production-key
    MonitoringInterval: 1 minute
    RootVolumeType: gp3
    RootVolumeSize: 50
    RootVolumeIOPS: 3000

  aws:autoscaling:trigger:
    MeasureName: CPUUtilization
    Unit: Percent
    UpperThreshold: 70
    LowerThreshold: 20
    ScaleUpIncrement: 2
    ScaleDownIncrement: -1
    BreachDuration: 2
    Period: 2
    EvaluationPeriods: 2
    Statistic: Average

  # Load Balancer Configuration
  aws:elasticbeanstalk:environment:process:default:
    HealthCheckPath: /api/health
    HealthCheckTimeout: 15
    HealthyThresholdCount: 3
    UnhealthyThresholdCount: 5
    Interval: 30
    MatcherHTTPCode: 200
    Port: 80
    Protocol: HTTP
    StickinessEnabled: true
    StickinessLBCookieDuration: 86400

  aws:elbv2:loadbalancer:
    IdleTimeout: 60
    SecurityGroups: sg-xxxxxxxxxxxxxxxxx
    ManagedSecurityGroup: sg-xxxxxxxxxxxxxxxxx

  aws:elbv2:listener:443:
    ListenerEnabled: true
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    SSLPolicy: ELBSecurityPolicy-TLS-1-2-2017-01

  # VPC Configuration
  aws:ec2:vpc:
    VPCId: vpc-xxxxxxxxxxxxxxxxx
    Subnets: subnet-xxxxxxxxxxxxxxxxx,subnet-yyyyyyyyyyyyyyyyy,subnet-zzzzzzzzzzzzzzzzz
    ELBSubnets: subnet-xxxxxxxxxxxxxxxxx,subnet-yyyyyyyyyyyyyyyyy,subnet-zzzzzzzzzzzzzzzzz
    ELBScheme: internet-facing
    AssociatePublicIpAddress: false

  # CloudWatch Logs
  aws:elasticbeanstalk:cloudwatch:logs:
    StreamLogs: true
    DeleteOnTerminate: false
    RetentionInDays: 30

  aws:elasticbeanstalk:cloudwatch:logs:health:
    HealthStreamingEnabled: true
    DeleteOnTerminate: false
    RetentionInDays: 7

  # Managed Platform Updates
  aws:elasticbeanstalk:managedactions:
    ManagedActionsEnabled: true
    PreferredStartTime: Sun:03:00
    ServiceRoleForManagedUpdates: aws-elasticbeanstalk-service-role

  aws:elasticbeanstalk:managedactions:platformupdate:
    UpdateLevel: minor
    InstanceRefreshEnabled: true

  # Health Monitoring
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
    HealthCheckSuccessThreshold: Ok
    EnhancedHealthAuthEnabled: true

  # Container Configuration (Updated for Vite)
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: npm start
    NodeVersion: 18.19.0
    GzipCompression: true
    ProxyServer: nginx

  aws:elasticbeanstalk:container:nodejs:staticfiles:
    /assets: dist/assets
    /static: dist/assets
    /images: dist/images
    /favicon.ico: dist/favicon.ico
    /manifest.json: dist/manifest.json
    /site.webmanifest: dist/site.webmanifest
    /robots.txt: dist/robots.txt
    /api: public/api

# Build Configuration (Updated for Vite)
commands:
  01_update_npm:
    command: npm install -g npm@latest
  02_install_serve:
    command: npm install -g serve@latest
  03_install_dependencies:
    command: npm ci --include=dev --prefer-offline --no-audit
  04_typecheck:
    command: npm run typecheck
  05_build_production:
    command: NODE_ENV=production GENERATE_SOURCEMAP=false npm run build:production
  06_prepare_package_json:
    command: |
      cat > package.json << 'EOF'
      {
        "name": "quantumvest-enterprise",
        "version": "2.1.0",
        "scripts": {
          "start": "serve -s dist -l 8080"
        },
        "dependencies": {
          "serve": "^14.2.1"
        }
      }
      EOF
  07_install_serve_local:
    command: npm install

# Files to include in deployment
files:
  "/opt/elasticbeanstalk/hooks/appdeploy/pre/01_install_dependencies.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/bash
      # Install system dependencies for enterprise features
      yum update -y
      yum install -y htop iotop
      npm install -g pm2

  "/opt/elasticbeanstalk/hooks/appdeploy/post/01_enterprise_setup.sh":
    mode: "000755"
    owner: root
    group: root
    content: |
      #!/bin/bash
      # Enterprise post-deployment setup
      echo "Setting up enterprise monitoring..."
      # Configure CloudWatch agent
      # Setup custom metrics
      # Configure log rotation
      echo "Enterprise setup completed"

  "/etc/nginx/conf.d/enterprise.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      # Enterprise Nginx Configuration
      server {
          listen 80;
          server_name quantumvest.app www.quantumvest.app;

          # Security headers
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;
          add_header X-XSS-Protection "1; mode=block";
          add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
          add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googletagmanager.com *.google-analytics.com *.hotjar.com *.mixpanel.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: *.google-analytics.com *.googletagmanager.com; connect-src 'self' *.supabase.co wss://*.supabase.co *.google-analytics.com *.mixpanel.com *.hotjar.com api.quantumvest.app ws.quantumvest.app";

          # Compression
          gzip on;
          gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
          gzip_min_length 1000;

          # Cache headers
          location /static/ {
              expires 1y;
              add_header Cache-Control "public, immutable";
          }

          # API proxy
          location /api/ {
              proxy_pass https://api.quantumvest.app;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }

          # WebSocket proxy
          location /ws/ {
              proxy_pass https://ws.quantumvest.app;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

# Deployment Configuration
deploy:
  application_name: quantumvest-enterprise
  environment_name: quantumvest-production
  region: us-east-1
  artifact: quantumvest-enterprise.zip

  # Blue/Green Deployment
  deployment_policy: RollingWithAdditionalBatch
  deployment_batch_size_type: Fixed
  deployment_batch_size: 2

  # Health Check Configuration
  health_check_type: ELB
  health_check_grace_period: 300

  # Rollback Configuration
  enable_rollback: true
  rollback_triggers:
    - CloudWatchAlarm: HighErrorRate
    - CloudWatchAlarm: HighLatency
    - CloudWatchAlarm: LowHealthyHosts

# Resource Tags
tags:
  Project: QuantumVest
  Environment: Production
  Tier: Enterprise
  Owner: Platform Team
  CostCenter: Engineering
  Compliance: SOC2-GDPR-PCI
  BackupRequired: true
  MonitoringLevel: Enhanced

# Monitoring & Alerting
monitoring:
  cloudwatch_alarms:
    - name: HighErrorRate
      metric: ApplicationRequestsTotal
      threshold: 50
      comparison: GreaterThanThreshold
      period: 300
      evaluation_periods: 2

    - name: HighLatency
      metric: ApplicationLatencyP99
      threshold: 2000
      comparison: GreaterThanThreshold
      period: 300
      evaluation_periods: 2

    - name: LowHealthyHosts
      metric: ApplicationTargetsHealthy
      threshold: 1
      comparison: LessThanThreshold
      period: 60
      evaluation_periods: 1

# Security Configuration
security:
  waf_enabled: true
  ddos_protection: true
  ssl_certificate: arn:aws:acm:us-east-1:xxxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  security_groups:
    - sg-xxxxxxxxxxxxxxxxx # Web tier
    - sg-yyyyyyyyyyyyyyyyy # Application tier
    - sg-zzzzzzzzzzzzzzzzz # Database tier

# Backup Configuration
backup:
  enabled: true
  retention_days: 30
  backup_window: "03:00-05:00"
  maintenance_window: "sun:05:00-sun:07:00"

# Performance Optimization
performance:
  cloudfront_enabled: true
  s3_static_hosting: true
  redis_caching: true
  database_read_replicas: 2
  cdn_cache_ttl: 86400

# Cost Optimization
cost_optimization:
  spot_instances: false
  reserved_instances: true
  instance_scheduler: true
  lifecycle_policies: true
